# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import telemetry_service_pb2 as telemetry__service__pb2


class TelemetryServiceStub(object):
  """Telemetry Service
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetAttitudeQ = channel.unary_unary(
        '/telemetry.TelemetryService/GetAttitudeQ',
        request_serializer=telemetry__service__pb2.AttitudeQRequest.SerializeToString,
        response_deserializer=telemetry__service__pb2.AttitudeQResponse.FromString,
        )
    self.GetAttitudeStream = channel.unary_stream(
        '/telemetry.TelemetryService/GetAttitudeStream',
        request_serializer=telemetry__service__pb2.AttitudeQRequest.SerializeToString,
        response_deserializer=telemetry__service__pb2.AttitudeQResponse.FromString,
        )
    self.hitEvent = channel.unary_unary(
        '/telemetry.TelemetryService/hitEvent',
        request_serializer=telemetry__service__pb2.HitEvent.SerializeToString,
        response_deserializer=telemetry__service__pb2.EventResponse.FromString,
        )
    self.headingEvent = channel.unary_unary(
        '/telemetry.TelemetryService/headingEvent',
        request_serializer=telemetry__service__pb2.HeadingEvent.SerializeToString,
        response_deserializer=telemetry__service__pb2.EventResponse.FromString,
        )
    self.setTarget = channel.unary_unary(
        '/telemetry.TelemetryService/setTarget',
        request_serializer=telemetry__service__pb2.Waypoint.SerializeToString,
        response_deserializer=telemetry__service__pb2.NoContent.FromString,
        )
    self.setWaypoints = channel.unary_unary(
        '/telemetry.TelemetryService/setWaypoints',
        request_serializer=telemetry__service__pb2.Waypoints.SerializeToString,
        response_deserializer=telemetry__service__pb2.NoContent.FromString,
        )


class TelemetryServiceServicer(object):
  """Telemetry Service
  """

  def GetAttitudeQ(self, request, context):
    """Simple RPC
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAttitudeStream(self, request, context):
    """Server to client streaming RPC
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def hitEvent(self, request, context):
    """Event Registration
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def headingEvent(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def setTarget(self, request, context):
    """Navigation
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def setWaypoints(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TelemetryServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetAttitudeQ': grpc.unary_unary_rpc_method_handler(
          servicer.GetAttitudeQ,
          request_deserializer=telemetry__service__pb2.AttitudeQRequest.FromString,
          response_serializer=telemetry__service__pb2.AttitudeQResponse.SerializeToString,
      ),
      'GetAttitudeStream': grpc.unary_stream_rpc_method_handler(
          servicer.GetAttitudeStream,
          request_deserializer=telemetry__service__pb2.AttitudeQRequest.FromString,
          response_serializer=telemetry__service__pb2.AttitudeQResponse.SerializeToString,
      ),
      'hitEvent': grpc.unary_unary_rpc_method_handler(
          servicer.hitEvent,
          request_deserializer=telemetry__service__pb2.HitEvent.FromString,
          response_serializer=telemetry__service__pb2.EventResponse.SerializeToString,
      ),
      'headingEvent': grpc.unary_unary_rpc_method_handler(
          servicer.headingEvent,
          request_deserializer=telemetry__service__pb2.HeadingEvent.FromString,
          response_serializer=telemetry__service__pb2.EventResponse.SerializeToString,
      ),
      'setTarget': grpc.unary_unary_rpc_method_handler(
          servicer.setTarget,
          request_deserializer=telemetry__service__pb2.Waypoint.FromString,
          response_serializer=telemetry__service__pb2.NoContent.SerializeToString,
      ),
      'setWaypoints': grpc.unary_unary_rpc_method_handler(
          servicer.setWaypoints,
          request_deserializer=telemetry__service__pb2.Waypoints.FromString,
          response_serializer=telemetry__service__pb2.NoContent.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'telemetry.TelemetryService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
